/* Cross-engine parity test: replays tests/test_vectors.json (generated by
 * the Python engine) against the JS engine and requires agreement to 1e-9
 * relative tolerance on every numeric result and every check verdict.
 *
 * Run:  node web/test_core.mjs
 */
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import { createRequire } from "node:module";

const here = dirname(fileURLToPath(import.meta.url));
const require = createRequire(import.meta.url);
const pv = require(join(here, "pvcalc-core.js"));
const vectors = JSON.parse(readFileSync(join(here, "..", "tests", "test_vectors.json"), "utf-8"));

let failures = 0, checked = 0;

for (const [i, v] of vectors.entries()) {
  const fn = pv[v.fn];
  if (!fn) { console.log(`[FAIL] #${i} unknown fn ${v.fn}`); failures++; continue; }
  // weldStrength / flangeStresses consume an earlier result — replay both calls.
  let r;
  if (v.fn === "weldStrength")
    r = pv.weldStrength(pv.areaReinforcement(v.kwargs.area), v.kwargs.weld);
  else if (v.fn === "largeOpeningCheck")
    r = pv.largeOpeningCheck(pv.areaReinforcement(v.kwargs.area), v.kwargs.large);
  else if (v.fn === "flangeStresses")
    r = pv.flangeStresses(pv.flangeBoltLoads(v.kwargs.bolt), v.kwargs.stress);
  // a650ShellCourses 는 {courses, summary} 를 돌려준다 — 파이썬은 요약만 기록.
  else if (v.fn === "a650ShellCourses")
    r = pv.a650ShellCourses(v.kwargs).summary;
  else if (v.fn === "a650VdpCourses")
    r = pv.a650VdpCourses(v.kwargs).summary;
  else
    r = fn(v.kwargs);
  for (const [key, expected] of Object.entries(v.results)) {
    const actual = r.results[key];
    checked++;
    const ok = typeof actual === "number" &&
      (Math.abs(actual - expected) <= 1e-9 * Math.max(1, Math.abs(expected)));
    if (!ok) {
      console.log(`[FAIL] #${i} ${v.fn} ${key}: js=${actual} py=${expected}`);
      console.log(`       kwargs: ${JSON.stringify(v.kwargs)}`);
      failures++;
    }
  }
  const jsChecks = r.checks.map(c => c[1]);
  if (JSON.stringify(jsChecks) !== JSON.stringify(v.checks)) {
    console.log(`[FAIL] #${i} ${v.fn} check verdicts differ: js=${jsChecks} py=${v.checks}`);
    failures++;
  }
  checked++;
}

// thickness-for-external inversion sanity (not vector-based)
const tMin = pv.cylinderThicknessForExternal(
  { P_ext: 0.239, Do: 2000, L: 3000, Ey: 195000, Sy: 205 });
if (!(tMin > 9.9 && tMin < 10.1)) {
  console.log(`[FAIL] cylinderThicknessForExternal: got ${tMin}`); failures++;
}
checked++;

console.log(`${vectors.length} vectors, ${checked} comparisons, ${failures} failure(s)`);
process.exit(failures ? 1 : 0);
